### ISSUE TITLE
seletores duplicados

### ISSUE THREAD

**Issue by batusa** [metal/steel-avatar#1]
rapidamente visualizando o código css, percebi que haviam algumas duplicações em seletores.

[L146-L147](https://github.com/metal/steel-avatar/blob/master/src/avatar.scss#L146-L147)
[L159-L160](https://github.com/metal/steel-avatar/blob/master/src/avatar.scss#L159-L160)
[L172-L173](https://github.com/metal/steel-avatar/blob/master/src/avatar.scss#L172-L173)
[L185-L186](https://github.com/metal/steel-avatar/blob/master/src/avatar.scss#L185-L186)

**Comment by zenorocha** [comment]
Nope they are not duplicated, those are all different selectors.

P.S.: Issues must be filled in English

**Comment by batusa** [comment]
sorry, I didn't know about that. @zenorocha

**Comment by eduardolundgren** [comment]
Those aren't the same?

```
.avatar-icon-12.avatar-medium span,
.avatar-icon-12.avatar-medium span {
```

**Comment by zenorocha** [comment]
Actually, they are. Sorry, my mistake.

**Comment by batusa** [comment]
:+1:
